//Throwing userdefined exception... 

public class TestThrow3 {
    public static void main(String[] args) {
        
    }
}
